[package]
name = "rgrit-proc"
version = "0.1.0"
edition = "2021"

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
rgrit-rs = { path = "../rgrit-rs" }
rgrit-core = { path = "../rgrit-core" }

[lib]
proc-macro = true
