[package]
name = "grit-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
grit-sys = { path = "../grit-sys" }
thiserror = "2.0.9"
quote.workspace = true
proc-macro2.workspace = true
syn.workspace = true
